backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: site/static/images
collections:
  - name: "page"
    label: "Page"
    folder: "site/content"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "what-we-do"
    label: "Service"
    folder: "site/content/what-we-do"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "ParentUrl",
          name: "parenturl",
          widget: "hidden",
          default: "/what-we-do/",
        }
